version: '3.8'

services:
  smart-consultant-client:
    build: .
    image: faruoq01/ai-in-action:smart-consultant-client
    container_name: smart-consultant-client
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped


# docker buildx create --use
# docker buildx build --platform linux/amd64 -t faruoq01/ai-in-action:smart-consultant-client --push .