name: Deploy on Merge

on:
  push:
    branches:
      - main  # run this workflow on pushes to main (merges)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run deployment script on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}        
        username: ${{ secrets.SERVER_USER }}    
        key: ${{ secrets.SERVER_SSH_KEY }}      
        script: |
          echo "Current working dir: $(pwd)"
          cd /home/ai-in-action
          ls -l
          ./deploy.sh
